#!/usr/bin/env node
/**
 * Packages the relay as one file: envelope-relay.exe (or a plain
 * "envelope-relay" binary on macOS/Linux). No Node.js install is needed to
 * run the result — it's a copy of `node` itself with the relay's code
 * injected, using Node's built-in Single Executable Application feature.
 *
 * Run from this folder: node build-exe.mjs
 * Output: dist/envelope-relay.exe
 */
import { build } from 'esbuild'
import { execFileSync } from 'node:child_process'
import { copyFileSync, chmodSync, mkdirSync } from 'node:fs'
import { platform } from 'node:process'

const dir = import.meta.dirname
const dist = `${dir}/dist`
mkdirSync(dist, { recursive: true })

console.log('1/4 bundling index.js + ws into one file…')
await build({
  entryPoints: [`${dir}/index.js`],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  outfile: `${dist}/relay-bundle.cjs`,
  banner: { js: '// envelope-relay bundle — generated by build-exe.mjs, do not edit' },
})

console.log('2/4 building the SEA blob…')
execFileSync(process.execPath, ['--experimental-sea-config', `${dir}/sea-config.json`], { stdio: 'inherit', cwd: dir })

const exeName = platform === 'win32' ? 'envelope-relay.exe' : 'envelope-relay'
const exePath = `${dist}/${exeName}`
console.log(`3/4 copying node -> ${exeName}…`)
copyFileSync(process.execPath, exePath)
if (platform !== 'win32') chmodSync(exePath, 0o755)

console.log('4/4 injecting the blob…')
const postjectCli = `${dir}/node_modules/postject/dist/cli.js`
const fuse = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2'
const args = [postjectCli, exePath, 'NODE_SEA_BLOB', `${dist}/sea-prep.blob`, '--sentinel-fuse', fuse]
if (platform === 'darwin') args.push('--macho-segment-name', 'NODE_SEA')
execFileSync(process.execPath, args, { stdio: 'inherit' })

console.log(`\nDone: dist/${exeName}`)
console.log(platform === 'win32' ? `Run it directly: .\\dist\\${exeName}` : `Run it directly: ./dist/${exeName}`)
if (platform === 'win32') console.log('First run: Windows SmartScreen may warn because this .exe is unsigned. Click "More info" -> "Run anyway".')
